language: node_js
node_js:
  - 10

install:
  - "npm install"

script:
  - "npm run test"
  - "npm run test:coverage"
  - "npm run lint"

before_install:
  - pip install --user codecov

after_success:
  - codecov